/** @type {import('next').NextConfig} */
const nextConfig = {
  // End-credits résumé (static page generated by github.com/ruisnow-e/ruisnow-e)
  async rewrites() {
    return [{ source: "/credits", destination: "/credits.html" }];
  },
};

export default nextConfig;
